from datetime import date

from fastapi import APIRouter, Depends, HTTPException, Response, status
from sqlalchemy.orm import Session

from app.api.deps import get_current_user, get_db
from app.models.user import User
from app.schemas.plan import (
    PlanAutogenerateRequest,
    PlanAutogenerateResponse,
    PlanCreate,
    PlanListItem,
    PlanRead,
    RegeneratePlanDayRequest,
    ReplacePlanSlotRequest,
    PlanSlotRead,
    PlanSlotUpdate,
)
from app.schemas.shopping import (
    ShoppingListItemRead,
    ShoppingListRead,
    ShoppingManualItemCreate,
    ShoppingManualItemRead,
    ShoppingOverrideUpdate,
)
from app.services.plan_autogenerate import (
    PlanAutogenerateDayOutOfRangeError,
    PlanAutogenerateNotEnoughRecipesError,
    PlanAutogeneratePlanNotFoundError,
    PlanAutogenerateProfileNotFoundError,
    PlanAutogenerateProfileValidationError,
    PlanAutogenerateSlotNotFoundError,
    build_autogenerated_plan,
    regenerate_plan_day,
    replace_plan_slot,
)
from app.services.plans import (
    PlanNotFoundError,
    PlanSlotNotFoundError,
    PlanSlotRecipeNotFoundError,
    build_plan_list_item,
    build_plan_read,
    build_plan_slot_read,
    create_plan,
    delete_plan_for_user,
    get_plan_for_user,
    list_plans_for_user,
    update_plan_slot,
)
from app.services.shopping import (
    ShoppingFoodNotFoundError,
    ShoppingManualItemNotFoundError,
    ShoppingPlanNotFoundError,
    create_manual_shopping_item,
    delete_manual_shopping_item,
    get_plan_shopping_list,
    update_shopping_override,
)

router = APIRouter(prefix="/plans", tags=["plans"])


@router.get("", response_model=list[PlanListItem])
def get_plans(
    db: Session = Depends(get_db),
    current_user: User = Depends(get_current_user),
):
    plans = list_plans_for_user(db, current_user.id)
    return [build_plan_list_item(plan) for plan in plans]


@router.post("", response_model=PlanRead, status_code=status.HTTP_201_CREATED)
def post_plan(
    payload: PlanCreate,
    db: Session = Depends(get_db),
    current_user: User = Depends(get_current_user),
):
    plan = create_plan(db, current_user.id, payload)
    return build_plan_read(plan)


@router.post("/autogenerate", response_model=PlanAutogenerateResponse, status_code=status.HTTP_201_CREATED)
def post_plan_autogenerate(
    payload: PlanAutogenerateRequest,
    db: Session = Depends(get_db),
    current_user: User = Depends(get_current_user),
):
    try:
        plan = build_autogenerated_plan(
            db,
            user_id=current_user.id,
            payload=payload,
        )
    except PlanAutogenerateProfileNotFoundError as exc:
        raise HTTPException(status_code=status.HTTP_404_NOT_FOUND, detail=str(exc)) from exc
    except PlanAutogenerateProfileValidationError as exc:
        raise HTTPException(status_code=status.HTTP_422_UNPROCESSABLE_ENTITY, detail=str(exc)) from exc
    except PlanAutogenerateNotEnoughRecipesError as exc:
        raise HTTPException(status_code=status.HTTP_422_UNPROCESSABLE_ENTITY, detail=str(exc)) from exc

    return build_plan_read(plan)


@router.post("/{plan_id}/slots/{slot_id}/replace", response_model=PlanRead)
def post_plan_slot_replace(
    plan_id: int,
    slot_id: int,
    payload: ReplacePlanSlotRequest,
    db: Session = Depends(get_db),
    current_user: User = Depends(get_current_user),
):
    try:
        plan = replace_plan_slot(
            db,
            user_id=current_user.id,
            plan_id=plan_id,
            slot_id=slot_id,
            payload=payload,
        )
    except PlanAutogeneratePlanNotFoundError as exc:
        raise HTTPException(status_code=status.HTTP_404_NOT_FOUND, detail="Plan not found") from exc
    except PlanAutogenerateSlotNotFoundError as exc:
        raise HTTPException(status_code=status.HTTP_404_NOT_FOUND, detail="Plan slot not found") from exc
    except PlanAutogenerateNotEnoughRecipesError as exc:
        raise HTTPException(status_code=status.HTTP_422_UNPROCESSABLE_ENTITY, detail=str(exc)) from exc

    return build_plan_read(plan)


@router.post("/{plan_id}/days/{day_date}/regenerate", response_model=PlanRead)
def post_plan_day_regenerate(
    plan_id: int,
    day_date: date,
    payload: RegeneratePlanDayRequest,
    db: Session = Depends(get_db),
    current_user: User = Depends(get_current_user),
):
    try:
        plan = regenerate_plan_day(
            db,
            user_id=current_user.id,
            plan_id=plan_id,
            day_date=day_date,
            payload=payload,
        )
    except PlanAutogeneratePlanNotFoundError as exc:
        raise HTTPException(status_code=status.HTTP_404_NOT_FOUND, detail="Plan not found") from exc
    except PlanAutogenerateDayOutOfRangeError as exc:
        raise HTTPException(status_code=status.HTTP_422_UNPROCESSABLE_ENTITY, detail=str(exc)) from exc
    except PlanAutogenerateNotEnoughRecipesError as exc:
        raise HTTPException(status_code=status.HTTP_422_UNPROCESSABLE_ENTITY, detail=str(exc)) from exc

    return build_plan_read(plan)


@router.get("/{plan_id}", response_model=PlanRead)
def get_plan_by_id(
    plan_id: int,
    db: Session = Depends(get_db),
    current_user: User = Depends(get_current_user),
):
    try:
        plan = get_plan_for_user(db, current_user.id, plan_id)
    except PlanNotFoundError as exc:
        raise HTTPException(status_code=status.HTTP_404_NOT_FOUND, detail="Plan not found") from exc
    return build_plan_read(plan)


@router.delete("/{plan_id}", status_code=status.HTTP_204_NO_CONTENT)
def delete_plan_by_id(
    plan_id: int,
    db: Session = Depends(get_db),
    current_user: User = Depends(get_current_user),
):
    try:
        delete_plan_for_user(db, current_user.id, plan_id)
    except PlanNotFoundError as exc:
        raise HTTPException(status_code=status.HTTP_404_NOT_FOUND, detail="Plan not found") from exc
    return Response(status_code=status.HTTP_204_NO_CONTENT)


@router.patch("/{plan_id}/slots/{slot_id}", response_model=PlanSlotRead)
def patch_plan_slot(
    plan_id: int,
    slot_id: int,
    payload: PlanSlotUpdate,
    db: Session = Depends(get_db),
    current_user: User = Depends(get_current_user),
):
    try:
        slot = update_plan_slot(db, current_user.id, plan_id, slot_id, payload)
    except PlanNotFoundError as exc:
        raise HTTPException(status_code=status.HTTP_404_NOT_FOUND, detail="Plan not found") from exc
    except PlanSlotNotFoundError as exc:
        raise HTTPException(status_code=status.HTTP_404_NOT_FOUND, detail="Plan slot not found") from exc
    except PlanSlotRecipeNotFoundError as exc:
        raise HTTPException(status_code=status.HTTP_404_NOT_FOUND, detail="Recipe not found") from exc
    return build_plan_slot_read(slot)


@router.get("/{plan_id}/shopping-list", response_model=ShoppingListRead)
def get_plan_shopping(
    plan_id: int,
    db: Session = Depends(get_db),
    current_user: User = Depends(get_current_user),
):
    try:
        return get_plan_shopping_list(db, current_user.id, plan_id)
    except ShoppingPlanNotFoundError as exc:
        raise HTTPException(status_code=status.HTTP_404_NOT_FOUND, detail="Plan not found") from exc


@router.patch("/{plan_id}/shopping-list/{food_id}", response_model=ShoppingListItemRead)
def patch_plan_shopping_item(
    plan_id: int,
    food_id: int,
    payload: ShoppingOverrideUpdate,
    db: Session = Depends(get_db),
    current_user: User = Depends(get_current_user),
):
    try:
        return update_shopping_override(db, current_user.id, plan_id, food_id, payload)
    except ShoppingPlanNotFoundError as exc:
        raise HTTPException(status_code=status.HTTP_404_NOT_FOUND, detail="Plan not found") from exc
    except ShoppingFoodNotFoundError as exc:
        raise HTTPException(status_code=status.HTTP_404_NOT_FOUND, detail="Shopping item not found") from exc


@router.post("/{plan_id}/shopping-list/manual", response_model=ShoppingManualItemRead, status_code=status.HTTP_201_CREATED)
def post_plan_shopping_manual_item(
    plan_id: int,
    payload: ShoppingManualItemCreate,
    db: Session = Depends(get_db),
    current_user: User = Depends(get_current_user),
):
    try:
        manual_item = create_manual_shopping_item(db, current_user.id, plan_id, payload)
    except ShoppingPlanNotFoundError as exc:
        raise HTTPException(status_code=status.HTTP_404_NOT_FOUND, detail="Plan not found") from exc
    return ShoppingManualItemRead.model_validate(manual_item)


@router.delete("/{plan_id}/shopping-list/manual/{manual_item_id}", status_code=status.HTTP_204_NO_CONTENT)
def delete_plan_shopping_manual_item(
    plan_id: int,
    manual_item_id: int,
    db: Session = Depends(get_db),
    current_user: User = Depends(get_current_user),
):
    try:
        delete_manual_shopping_item(db, current_user.id, plan_id, manual_item_id)
    except ShoppingPlanNotFoundError as exc:
        raise HTTPException(status_code=status.HTTP_404_NOT_FOUND, detail="Plan not found") from exc
    except ShoppingManualItemNotFoundError as exc:
        raise HTTPException(status_code=status.HTTP_404_NOT_FOUND, detail="Manual shopping item not found") from exc
    return Response(status_code=status.HTTP_204_NO_CONTENT)
