from datetime import date

from fastapi import APIRouter, Depends, HTTPException, Response, status
from sqlalchemy.orm import Session

from app.api.deps import get_current_user, get_db
from app.models.user import User
from app.schemas.plan import (
    PlanAnalyticsResponse,
    PlanSlotEffectiveIngredientsResponse,
    PlanSlotIngredientOverridesReplaceRequest,
    PlanAutogenerateRequest,
    PlanAutogenerateResponse,
    PlanBulkDeleteRequest,
    PlanBulkDeleteResponse,
    PlanCreate,
    PlanListItem,
    PlanRead,
    RegeneratePlanDayRequest,
    ReplacePlanSlotRequest,
    PlanSlotRead,
    PlanSlotUpdate,
)
from app.services.plan_analytics import (
    PlanAnalyticsTargetsMissingError,
    get_plan_analytics_for_user,
)
from app.schemas.shopping import (
    ShoppingListRead,
)
from app.services.plan_autogenerate import (
    PlanAutogenerateDayOutOfRangeError,
    PlanAutogenerateLowFeasibilityError,
    PlanAutogenerateNotEnoughRecipesError,
    PlanAutogeneratePlanNotFoundError,
    PlanAutogenerateProfileNotFoundError,
    PlanAutogenerateProfileValidationError,
    PlanAutogenerateSlotNotFoundError,
    autogenerate_plan,
    regenerate_day,
    replace_slot,
)
from app.services.plans import (
    PlanNotFoundError,
    PlanProfileNotFoundError,
    PlanSlotNotFoundError,
    PlanSlotRecipeNotFoundError,
    build_plan_list_item,
    build_plan_read,
    build_plan_slot_read,
    create_plan,
    delete_plans_for_user,
    delete_plan_for_user,
    get_plan_for_user,
    list_plans_for_user,
    update_plan_slot,
)
from app.services.plan_slot_ingredients import (
    PlanSlotIngredientsFoodNotFoundError,
    PlanSlotIngredientsPlanNotFoundError,
    PlanSlotIngredientsRecipeIngredientInvalidError,
    PlanSlotIngredientsRecipeRequiredError,
    PlanSlotIngredientsSlotNotFoundError,
    delete_slot_ingredient_overrides,
    get_slot_effective_ingredients,
    replace_slot_ingredient_overrides,
)
from app.services.shopping import (
    ShoppingPlanNotFoundError,
    get_or_create_shopping_list_for_plan,
)

router = APIRouter(prefix="/plans", tags=["plans"])


@router.get("", response_model=list[PlanListItem])
def get_plans(
    db: Session = Depends(get_db),
    current_user: User = Depends(get_current_user),
):
    plans = list_plans_for_user(db, current_user.id)
    return [build_plan_list_item(plan) for plan in plans]


@router.post("", response_model=PlanRead, status_code=status.HTTP_201_CREATED)
def post_plan(
    payload: PlanCreate,
    db: Session = Depends(get_db),
    current_user: User = Depends(get_current_user),
):
    try:
        plan = create_plan(db, current_user.id, payload)
    except PlanProfileNotFoundError as exc:
        raise HTTPException(status_code=status.HTTP_404_NOT_FOUND, detail="Profile not found") from exc
    return build_plan_read(plan)


@router.post("/autogenerate", response_model=PlanAutogenerateResponse, status_code=status.HTTP_201_CREATED)
def post_plan_autogenerate(
    payload: PlanAutogenerateRequest,
    db: Session = Depends(get_db),
    current_user: User = Depends(get_current_user),
):
    try:
        plan = autogenerate_plan(
            db,
            user_id=current_user.id,
            payload=payload,
        )
    except PlanAutogenerateProfileNotFoundError as exc:
        raise HTTPException(status_code=status.HTTP_404_NOT_FOUND, detail=str(exc)) from exc
    except PlanAutogenerateProfileValidationError as exc:
        raise HTTPException(status_code=status.HTTP_422_UNPROCESSABLE_ENTITY, detail=str(exc)) from exc
    except PlanAutogenerateLowFeasibilityError as exc:
        raise HTTPException(status_code=status.HTTP_422_UNPROCESSABLE_ENTITY, detail=str(exc)) from exc
    except PlanAutogenerateNotEnoughRecipesError as exc:
        raise HTTPException(status_code=status.HTTP_422_UNPROCESSABLE_ENTITY, detail=str(exc)) from exc

    return build_plan_read(plan)


@router.post("/bulk-delete", response_model=PlanBulkDeleteResponse)
def post_plan_bulk_delete(
    payload: PlanBulkDeleteRequest,
    db: Session = Depends(get_db),
    current_user: User = Depends(get_current_user),
):
    try:
        return delete_plans_for_user(db, current_user.id, payload.plan_ids)
    except PlanNotFoundError as exc:
        raise HTTPException(status_code=status.HTTP_404_NOT_FOUND, detail="Plan not found") from exc


@router.post("/{plan_id}/slots/{slot_id}/replace", response_model=PlanRead)
def post_plan_slot_replace(
    plan_id: int,
    slot_id: int,
    payload: ReplacePlanSlotRequest | None = None,
    db: Session = Depends(get_db),
    current_user: User = Depends(get_current_user),
):
    normalized_payload = payload or ReplacePlanSlotRequest()
    try:
        plan = replace_slot(
            db,
            user_id=current_user.id,
            plan_id=plan_id,
            slot_id=slot_id,
            payload=normalized_payload,
        )
    except PlanAutogeneratePlanNotFoundError as exc:
        raise HTTPException(status_code=status.HTTP_404_NOT_FOUND, detail="Plan not found") from exc
    except PlanAutogenerateSlotNotFoundError as exc:
        raise HTTPException(status_code=status.HTTP_404_NOT_FOUND, detail="Plan slot not found") from exc
    except PlanAutogenerateNotEnoughRecipesError as exc:
        raise HTTPException(status_code=status.HTTP_422_UNPROCESSABLE_ENTITY, detail=str(exc)) from exc

    return build_plan_read(plan)


@router.post("/{plan_id}/days/{day_date}/regenerate", response_model=PlanRead)
def post_plan_day_regenerate(
    plan_id: int,
    day_date: date,
    payload: RegeneratePlanDayRequest,
    db: Session = Depends(get_db),
    current_user: User = Depends(get_current_user),
):
    try:
        plan = regenerate_day(
            db,
            user_id=current_user.id,
            plan_id=plan_id,
            day_date=day_date,
            payload=payload,
        )
    except PlanAutogeneratePlanNotFoundError as exc:
        raise HTTPException(status_code=status.HTTP_404_NOT_FOUND, detail="Plan not found") from exc
    except PlanAutogenerateDayOutOfRangeError as exc:
        raise HTTPException(status_code=status.HTTP_422_UNPROCESSABLE_ENTITY, detail=str(exc)) from exc
    except PlanAutogenerateNotEnoughRecipesError as exc:
        raise HTTPException(status_code=status.HTTP_422_UNPROCESSABLE_ENTITY, detail=str(exc)) from exc

    return build_plan_read(plan)


@router.get("/{plan_id}", response_model=PlanRead)
def get_plan_by_id(
    plan_id: int,
    db: Session = Depends(get_db),
    current_user: User = Depends(get_current_user),
):
    try:
        plan = get_plan_for_user(db, current_user.id, plan_id)
    except PlanNotFoundError as exc:
        raise HTTPException(status_code=status.HTTP_404_NOT_FOUND, detail="Plan not found") from exc
    return build_plan_read(plan)


@router.get("/{plan_id}/analytics", response_model=PlanAnalyticsResponse)
def get_plan_analytics(
    plan_id: int,
    db: Session = Depends(get_db),
    current_user: User = Depends(get_current_user),
):
    try:
        return get_plan_analytics_for_user(
            db,
            user_id=current_user.id,
            plan_id=plan_id,
        )
    except PlanNotFoundError as exc:
        raise HTTPException(status_code=status.HTTP_404_NOT_FOUND, detail="Plan not found") from exc
    except PlanAnalyticsTargetsMissingError as exc:
        raise HTTPException(status_code=status.HTTP_422_UNPROCESSABLE_ENTITY, detail=str(exc)) from exc


@router.delete("/{plan_id}", status_code=status.HTTP_204_NO_CONTENT)
def delete_plan_by_id(
    plan_id: int,
    db: Session = Depends(get_db),
    current_user: User = Depends(get_current_user),
):
    try:
        delete_plan_for_user(db, current_user.id, plan_id)
    except PlanNotFoundError as exc:
        raise HTTPException(status_code=status.HTTP_404_NOT_FOUND, detail="Plan not found") from exc
    return Response(status_code=status.HTTP_204_NO_CONTENT)


@router.patch("/{plan_id}/slots/{slot_id}", response_model=PlanSlotRead)
def patch_plan_slot(
    plan_id: int,
    slot_id: int,
    payload: PlanSlotUpdate,
    db: Session = Depends(get_db),
    current_user: User = Depends(get_current_user),
):
    try:
        slot = update_plan_slot(db, current_user.id, plan_id, slot_id, payload)
    except PlanNotFoundError as exc:
        raise HTTPException(status_code=status.HTTP_404_NOT_FOUND, detail="Plan not found") from exc
    except PlanSlotNotFoundError as exc:
        raise HTTPException(status_code=status.HTTP_404_NOT_FOUND, detail="Plan slot not found") from exc
    except PlanSlotRecipeNotFoundError as exc:
        raise HTTPException(status_code=status.HTTP_404_NOT_FOUND, detail="Recipe not found") from exc
    return build_plan_slot_read(slot)


@router.get("/{plan_id}/slots/{slot_id}/ingredients", response_model=PlanSlotEffectiveIngredientsResponse)
def get_plan_slot_ingredients(
    plan_id: int,
    slot_id: int,
    db: Session = Depends(get_db),
    current_user: User = Depends(get_current_user),
):
    try:
        return get_slot_effective_ingredients(
            db,
            user_id=current_user.id,
            plan_id=plan_id,
            slot_id=slot_id,
        )
    except PlanSlotIngredientsPlanNotFoundError as exc:
        raise HTTPException(status_code=status.HTTP_404_NOT_FOUND, detail="Plan not found") from exc
    except PlanSlotIngredientsSlotNotFoundError as exc:
        raise HTTPException(status_code=status.HTTP_404_NOT_FOUND, detail="Plan slot not found") from exc
    except PlanSlotIngredientsRecipeRequiredError as exc:
        raise HTTPException(status_code=status.HTTP_422_UNPROCESSABLE_ENTITY, detail=str(exc)) from exc


@router.put("/{plan_id}/slots/{slot_id}/ingredient-overrides", response_model=PlanSlotEffectiveIngredientsResponse)
def put_plan_slot_ingredient_overrides(
    plan_id: int,
    slot_id: int,
    payload: PlanSlotIngredientOverridesReplaceRequest,
    db: Session = Depends(get_db),
    current_user: User = Depends(get_current_user),
):
    try:
        return replace_slot_ingredient_overrides(
            db,
            user_id=current_user.id,
            plan_id=plan_id,
            slot_id=slot_id,
            payload=payload,
        )
    except PlanSlotIngredientsPlanNotFoundError as exc:
        raise HTTPException(status_code=status.HTTP_404_NOT_FOUND, detail="Plan not found") from exc
    except PlanSlotIngredientsSlotNotFoundError as exc:
        raise HTTPException(status_code=status.HTTP_404_NOT_FOUND, detail="Plan slot not found") from exc
    except PlanSlotIngredientsRecipeRequiredError as exc:
        raise HTTPException(status_code=status.HTTP_422_UNPROCESSABLE_ENTITY, detail=str(exc)) from exc
    except PlanSlotIngredientsRecipeIngredientInvalidError as exc:
        raise HTTPException(status_code=status.HTTP_422_UNPROCESSABLE_ENTITY, detail=str(exc)) from exc
    except PlanSlotIngredientsFoodNotFoundError as exc:
        raise HTTPException(status_code=status.HTTP_404_NOT_FOUND, detail=str(exc)) from exc


@router.delete("/{plan_id}/slots/{slot_id}/ingredient-overrides", response_model=PlanSlotEffectiveIngredientsResponse)
def delete_plan_slot_ingredient_overrides(
    plan_id: int,
    slot_id: int,
    db: Session = Depends(get_db),
    current_user: User = Depends(get_current_user),
):
    try:
        return delete_slot_ingredient_overrides(
            db,
            user_id=current_user.id,
            plan_id=plan_id,
            slot_id=slot_id,
        )
    except PlanSlotIngredientsPlanNotFoundError as exc:
        raise HTTPException(status_code=status.HTTP_404_NOT_FOUND, detail="Plan not found") from exc
    except PlanSlotIngredientsSlotNotFoundError as exc:
        raise HTTPException(status_code=status.HTTP_404_NOT_FOUND, detail="Plan slot not found") from exc
    except PlanSlotIngredientsRecipeRequiredError as exc:
        raise HTTPException(status_code=status.HTTP_422_UNPROCESSABLE_ENTITY, detail=str(exc)) from exc


@router.get("/{plan_id}/shopping-list", response_model=ShoppingListRead)
def get_plan_shopping(
    plan_id: int,
    db: Session = Depends(get_db),
    current_user: User = Depends(get_current_user),
):
    try:
        return get_or_create_shopping_list_for_plan(db, current_user.id, plan_id)
    except ShoppingPlanNotFoundError as exc:
        raise HTTPException(status_code=status.HTTP_404_NOT_FOUND, detail="Plan not found") from exc
