from __future__ import annotations

from collections import defaultdict
from datetime import date, timedelta
from decimal import Decimal

from sqlalchemy import and_, or_, select
from sqlalchemy.orm import Session, selectinload

from app.models.enums import FoodSource, FoodStatus
from app.models.plan import Plan
from app.models.plan_slot import PlanSlot
from app.models.recipe import Recipe, RecipeIngredient
from app.schemas.plan import (
    PlanAutogenerateRequest,
    RegeneratePlanDayRequest,
    ReplacePlanSlotRequest,
)

MEAL_TYPE_SEQUENCE_BY_MEALS_PER_DAY: dict[int, list[str]] = {
    2: ["breakfast", "dinner"],
    3: ["breakfast", "lunch", "dinner"],
    4: ["breakfast", "lunch", "dinner", "snack"],
    5: ["breakfast", "snack", "lunch", "dinner", "snack"],
    6: ["breakfast", "snack", "lunch", "snack", "dinner", "snack"],
}
ADJACENT_DAY_REPEAT_PENALTY = 100


class PlanAutogenerateNotEnoughRecipesError(ValueError):
    pass


class PlanAutogeneratePlanNotFoundError(ValueError):
    pass


class PlanAutogenerateSlotNotFoundError(ValueError):
    pass


class PlanAutogenerateDayOutOfRangeError(ValueError):
    pass


def get_meal_type_sequence(meals_per_day: int) -> list[str]:
    sequence = MEAL_TYPE_SEQUENCE_BY_MEALS_PER_DAY.get(meals_per_day)
    if sequence is None:
        raise ValueError("Unsupported meals_per_day")
    return list(sequence)


def get_accessible_recipe_candidates(
    db: Session,
    *,
    user_id: int,
    meal_type: str,
    use_public_recipes: bool,
    excluded_recipe_ids: list[int],
    excluded_food_ids: list[int],
) -> list[Recipe]:
    excluded_recipe_ids_set = set(excluded_recipe_ids)
    excluded_food_ids_set = set(excluded_food_ids)

    stmt = (
        select(Recipe)
        .options(selectinload(Recipe.ingredients).selectinload(RecipeIngredient.food))
        .where(
            or_(
                Recipe.owner_user_id == user_id,
                and_(
                    Recipe.source == FoodSource.community,
                    Recipe.status == FoodStatus.approved,
                    Recipe.is_listed.is_(True),
                ),
            )
        )
        .order_by(Recipe.id.asc())
    )
    if not use_public_recipes:
        stmt = stmt.where(Recipe.owner_user_id == user_id)
    if excluded_recipe_ids_set:
        stmt = stmt.where(Recipe.id.notin_(sorted(excluded_recipe_ids_set)))

    recipes = db.execute(stmt).scalars().all()
    candidates: list[Recipe] = []
    for recipe in recipes:
        normalized_recipe_meal_types = {value.strip().lower() for value in recipe.meal_types}
        if meal_type not in normalized_recipe_meal_types:
            continue
        if excluded_food_ids_set and any(ingredient.food_id in excluded_food_ids_set for ingredient in recipe.ingredients):
            continue
        candidates.append(recipe)
    return candidates


def score_recipe_candidate(
    recipe: Recipe,
    *,
    recipe_usage_counts: dict[int, int],
    previous_day_slot_recipe_id: int | None,
    candidates_count: int,
) -> tuple[int, int]:
    score = recipe_usage_counts.get(recipe.id, 0)
    if candidates_count > 1 and previous_day_slot_recipe_id == recipe.id:
        score += ADJACENT_DAY_REPEAT_PENALTY
    return score, recipe.id


def _raise_not_enough_recipes_error(*, meal_type: str, day_date: date) -> None:
    raise PlanAutogenerateNotEnoughRecipesError(
        f"Not enough recipes for meal_type={meal_type} on {day_date.isoformat()}"
    )


def _load_plan_with_slots_for_user(db: Session, *, user_id: int, plan_id: int) -> Plan:
    plan = db.execute(
        select(Plan)
        .where(Plan.id == plan_id, Plan.owner_user_id == user_id)
        .options(
            selectinload(Plan.slots)
            .selectinload(PlanSlot.recipe)
            .selectinload(Recipe.ingredients)
            .selectinload(RecipeIngredient.food)
        )
    ).scalar_one_or_none()
    if plan is None:
        raise PlanAutogeneratePlanNotFoundError("Plan not found")
    return plan


def _resolve_slot_meal_type(*, meals_per_day: int, slot_index: int) -> str:
    meal_type_sequence = get_meal_type_sequence(meals_per_day)
    return meal_type_sequence[slot_index]


def _build_recipe_usage_counts(
    *,
    slots: list[PlanSlot],
    excluded_slot_ids: set[int] | None = None,
) -> dict[int, int]:
    usage_counts: dict[int, int] = defaultdict(int)
    excluded_ids = excluded_slot_ids or set()
    for slot in slots:
        if slot.id in excluded_ids or slot.recipe_id is None:
            continue
        usage_counts[slot.recipe_id] += 1
    return usage_counts


def _find_previous_day_slot_recipe_id(
    *,
    slots: list[PlanSlot],
    day_date: date,
    slot_index: int,
) -> int | None:
    previous_day = day_date - timedelta(days=1)
    for slot in slots:
        if slot.day_date == previous_day and slot.slot_index == slot_index:
            return slot.recipe_id
    return None


def _select_recipe_id_for_slot(
    db: Session,
    *,
    user_id: int,
    meal_type: str,
    day_date: date,
    use_public_recipes: bool,
    excluded_recipe_ids: list[int],
    excluded_food_ids: list[int],
    avoid_recipe_ids: set[int],
    recipe_usage_counts: dict[int, int],
    previous_day_slot_recipe_id: int | None,
) -> int:
    candidates = get_accessible_recipe_candidates(
        db,
        user_id=user_id,
        meal_type=meal_type,
        use_public_recipes=use_public_recipes,
        excluded_recipe_ids=excluded_recipe_ids,
        excluded_food_ids=excluded_food_ids,
    )
    if avoid_recipe_ids:
        candidates = [candidate for candidate in candidates if candidate.id not in avoid_recipe_ids]
    if not candidates:
        _raise_not_enough_recipes_error(meal_type=meal_type, day_date=day_date)

    selected_recipe = min(
        candidates,
        key=lambda recipe: score_recipe_candidate(
            recipe,
            recipe_usage_counts=recipe_usage_counts,
            previous_day_slot_recipe_id=previous_day_slot_recipe_id,
            candidates_count=len(candidates),
        ),
    )
    return selected_recipe.id


def build_autogenerated_plan(
    db: Session,
    *,
    user_id: int,
    payload: PlanAutogenerateRequest,
) -> Plan:
    meal_type_sequence = get_meal_type_sequence(payload.meals_per_day)
    candidates_by_meal_type: dict[str, list[Recipe]] = {}
    for meal_type in sorted(set(meal_type_sequence)):
        candidates_by_meal_type[meal_type] = get_accessible_recipe_candidates(
            db,
            user_id=user_id,
            meal_type=meal_type,
            use_public_recipes=payload.use_public_recipes,
            excluded_recipe_ids=payload.excluded_recipe_ids,
            excluded_food_ids=payload.excluded_food_ids,
        )

    planned_slots: list[tuple[date, int, int]] = []
    recipe_usage_counts: dict[int, int] = defaultdict(int)
    previous_day_recipe_ids_by_slot_index: dict[int, int] = {}

    for day_offset in range(payload.days_count):
        day_date = payload.start_date + timedelta(days=day_offset)
        selected_recipe_ids_by_slot_index: dict[int, int] = {}
        for slot_index, meal_type in enumerate(meal_type_sequence):
            candidates = candidates_by_meal_type[meal_type]
            if not candidates:
                _raise_not_enough_recipes_error(meal_type=meal_type, day_date=day_date)

            previous_day_slot_recipe_id = previous_day_recipe_ids_by_slot_index.get(slot_index)
            selected_recipe = min(
                candidates,
                key=lambda recipe: score_recipe_candidate(
                    recipe,
                    recipe_usage_counts=recipe_usage_counts,
                    previous_day_slot_recipe_id=previous_day_slot_recipe_id,
                    candidates_count=len(candidates),
                ),
            )

            planned_slots.append((day_date, slot_index, selected_recipe.id))
            selected_recipe_ids_by_slot_index[slot_index] = selected_recipe.id
            recipe_usage_counts[selected_recipe.id] += 1

        previous_day_recipe_ids_by_slot_index = selected_recipe_ids_by_slot_index

    plan = Plan(
        owner_user_id=user_id,
        start_date=payload.start_date,
        days_count=payload.days_count,
        meals_per_day=payload.meals_per_day,
        title=None,
    )
    db.add(plan)
    db.flush()

    slots = [
        PlanSlot(
            plan_id=plan.id,
            day_date=day_date,
            slot_index=slot_index,
            recipe_id=recipe_id,
            servings_multiplier=Decimal("1"),
            pinned=False,
        )
        for day_date, slot_index, recipe_id in planned_slots
    ]
    db.add_all(slots)
    db.commit()

    return _load_plan_with_slots_for_user(db, user_id=user_id, plan_id=plan.id)


def replace_plan_slot(
    db: Session,
    *,
    user_id: int,
    plan_id: int,
    slot_id: int,
    payload: ReplacePlanSlotRequest,
) -> Plan:
    plan = _load_plan_with_slots_for_user(db, user_id=user_id, plan_id=plan_id)
    slot = next((value for value in plan.slots if value.id == slot_id), None)
    if slot is None:
        raise PlanAutogenerateSlotNotFoundError("Plan slot not found")

    meal_type = _resolve_slot_meal_type(meals_per_day=plan.meals_per_day, slot_index=slot.slot_index)
    recipe_usage_counts = _build_recipe_usage_counts(slots=list(plan.slots), excluded_slot_ids={slot.id})
    previous_day_slot_recipe_id = _find_previous_day_slot_recipe_id(
        slots=list(plan.slots),
        day_date=slot.day_date,
        slot_index=slot.slot_index,
    )

    avoid_recipe_ids: set[int] = set()
    if payload.avoid_current_recipe and slot.recipe_id is not None:
        avoid_recipe_ids.add(slot.recipe_id)

    selected_recipe_id = _select_recipe_id_for_slot(
        db,
        user_id=user_id,
        meal_type=meal_type,
        day_date=slot.day_date,
        use_public_recipes=payload.use_public_recipes,
        excluded_recipe_ids=payload.excluded_recipe_ids,
        excluded_food_ids=payload.excluded_food_ids,
        avoid_recipe_ids=avoid_recipe_ids,
        recipe_usage_counts=recipe_usage_counts,
        previous_day_slot_recipe_id=previous_day_slot_recipe_id,
    )

    slot.recipe_id = selected_recipe_id
    try:
        db.commit()
    except Exception:
        db.rollback()
        raise

    return _load_plan_with_slots_for_user(db, user_id=user_id, plan_id=plan.id)


def regenerate_plan_day(
    db: Session,
    *,
    user_id: int,
    plan_id: int,
    day_date: date,
    payload: RegeneratePlanDayRequest,
) -> Plan:
    plan = _load_plan_with_slots_for_user(db, user_id=user_id, plan_id=plan_id)
    end_date = plan.start_date + timedelta(days=plan.days_count - 1)
    if day_date < plan.start_date or day_date > end_date:
        raise PlanAutogenerateDayOutOfRangeError(
            f"Day {day_date.isoformat()} is out of plan range"
        )

    day_slots = sorted(
        [slot for slot in plan.slots if slot.day_date == day_date],
        key=lambda slot: (slot.slot_index, slot.id),
    )
    mutable_slots = [slot for slot in day_slots if not slot.pinned]
    if not mutable_slots:
        return plan

    mutable_slot_ids = {slot.id for slot in mutable_slots}
    recipe_usage_counts = _build_recipe_usage_counts(
        slots=list(plan.slots),
        excluded_slot_ids=mutable_slot_ids,
    )

    selected_recipe_id_by_slot_id: dict[int, int] = {}
    for slot in mutable_slots:
        meal_type = _resolve_slot_meal_type(meals_per_day=plan.meals_per_day, slot_index=slot.slot_index)
        previous_day_slot_recipe_id = _find_previous_day_slot_recipe_id(
            slots=list(plan.slots),
            day_date=day_date,
            slot_index=slot.slot_index,
        )
        selected_recipe_id = _select_recipe_id_for_slot(
            db,
            user_id=user_id,
            meal_type=meal_type,
            day_date=day_date,
            use_public_recipes=payload.use_public_recipes,
            excluded_recipe_ids=payload.excluded_recipe_ids,
            excluded_food_ids=payload.excluded_food_ids,
            avoid_recipe_ids=set(),
            recipe_usage_counts=recipe_usage_counts,
            previous_day_slot_recipe_id=previous_day_slot_recipe_id,
        )
        selected_recipe_id_by_slot_id[slot.id] = selected_recipe_id
        recipe_usage_counts[selected_recipe_id] += 1

    for slot in mutable_slots:
        slot.recipe_id = selected_recipe_id_by_slot_id[slot.id]

    try:
        db.commit()
    except Exception:
        db.rollback()
        raise

    return _load_plan_with_slots_for_user(db, user_id=user_id, plan_id=plan.id)
