from __future__ import annotations

from collections import defaultdict
from dataclasses import dataclass
from datetime import date, timedelta
from decimal import Decimal

from sqlalchemy import select
from sqlalchemy.orm import Session, selectinload

from app.models.plan import Plan
from app.models.plan_slot import PlanSlot
from app.models.profile import Profile
from app.models.recipe import Recipe, RecipeIngredient
from app.schemas.plan import (
    PlanAutogenerateRequest,
    RegeneratePlanDayRequest,
    ReplacePlanSlotRequest,
)
from app.services.recipes import build_accessible_recipes_condition, calculate_recipe_nutrients


@dataclass(frozen=True)
class SlotTemplate:
    meal_type: str
    weight: Decimal


@dataclass(frozen=True)
class PlanTargets:
    kcal: Decimal | None
    protein: Decimal | None
    fat: Decimal | None
    carbs: Decimal | None


@dataclass(frozen=True)
class RecipeScore:
    total_score: Decimal
    repeat_penalty: Decimal
    calorie_penalty: Decimal
    macro_penalty: Decimal
    slot_penalty: Decimal


SLOT_TEMPLATES_BY_MEALS_PER_DAY: dict[int, tuple[SlotTemplate, ...]] = {
    2: (
        SlotTemplate(meal_type="lunch", weight=Decimal("0.45")),
        SlotTemplate(meal_type="dinner", weight=Decimal("0.55")),
    ),
    3: (
        SlotTemplate(meal_type="breakfast", weight=Decimal("0.25")),
        SlotTemplate(meal_type="lunch", weight=Decimal("0.40")),
        SlotTemplate(meal_type="dinner", weight=Decimal("0.35")),
    ),
    4: (
        SlotTemplate(meal_type="breakfast", weight=Decimal("0.25")),
        SlotTemplate(meal_type="lunch", weight=Decimal("0.35")),
        SlotTemplate(meal_type="dinner", weight=Decimal("0.30")),
        SlotTemplate(meal_type="snack", weight=Decimal("0.10")),
    ),
    5: (
        SlotTemplate(meal_type="breakfast", weight=Decimal("0.20")),
        SlotTemplate(meal_type="snack", weight=Decimal("0.10")),
        SlotTemplate(meal_type="lunch", weight=Decimal("0.30")),
        SlotTemplate(meal_type="dinner", weight=Decimal("0.25")),
        SlotTemplate(meal_type="snack", weight=Decimal("0.15")),
    ),
    6: (
        SlotTemplate(meal_type="breakfast", weight=Decimal("0.20")),
        SlotTemplate(meal_type="snack", weight=Decimal("0.10")),
        SlotTemplate(meal_type="lunch", weight=Decimal("0.25")),
        SlotTemplate(meal_type="snack", weight=Decimal("0.10")),
        SlotTemplate(meal_type="dinner", weight=Decimal("0.25")),
        SlotTemplate(meal_type="snack", weight=Decimal("0.10")),
    ),
}

SERVINGS_MULTIPLIER_CANDIDATES: tuple[Decimal, ...] = (
    Decimal("0.75"),
    Decimal("1.00"),
    Decimal("1.25"),
    Decimal("1.50"),
    Decimal("1.75"),
    Decimal("2.00"),
)

CALORIE_PENALTY_WEIGHT = Decimal("120")
MACRO_PENALTY_WEIGHT = Decimal("28")
PROTEIN_OVERSHOOT_WEIGHT = Decimal("220")
FAT_OVERSHOOT_WEIGHT = Decimal("90")
CARBS_UNDERSHOOT_WEIGHT = Decimal("180")
REMAINING_BALANCE_WEIGHT = Decimal("130")
MACRO_PROFILE_PENALTY_WEIGHT = Decimal("140")
REPEAT_USAGE_PENALTY = Decimal("18")
REPEAT_SAME_SLOT_BY_DISTANCE: dict[int, Decimal] = {
    1: Decimal("120"),
    2: Decimal("70"),
    3: Decimal("30"),
    4: Decimal("12"),
}
FAR_REPEAT_SAME_SLOT_PENALTY = Decimal("4")
SLOT_MISMATCH_PENALTY = Decimal("10000")
HUGE_GUARDRAIL_PENALTY = Decimal("2500")
LARGE_SLOT_WEIGHT_THRESHOLD = Decimal("0.25")
PROTEIN_OVERSHOOT_HARD_LIMIT = Decimal("1.35")
CARBS_SO_FAR_GUARDRAIL_RATIO = Decimal("0.65")
PROTEIN_DENSE_MULTIPLIER_THRESHOLD = Decimal("1.50")
PROTEIN_DENSE_PER_SERVING_THRESHOLD = Decimal("35")
LOW_CARB_PER_SERVING_THRESHOLD = Decimal("22")
PROTEIN_DENSE_MULTIPLIER_CAP = Decimal("1.50")


class PlanAutogenerateNotEnoughRecipesError(ValueError):
    pass


class PlanAutogeneratePlanNotFoundError(ValueError):
    pass


class PlanAutogenerateSlotNotFoundError(ValueError):
    pass


class PlanAutogenerateDayOutOfRangeError(ValueError):
    pass


class PlanAutogenerateProfileNotFoundError(ValueError):
    pass


class PlanAutogenerateProfileValidationError(ValueError):
    pass


def get_slot_templates(meals_per_day: int) -> tuple[SlotTemplate, ...]:
    templates = SLOT_TEMPLATES_BY_MEALS_PER_DAY.get(meals_per_day)
    if templates is None:
        raise ValueError("Unsupported meals_per_day")
    return templates


def get_meal_type_sequence(meals_per_day: int) -> list[str]:
    return [template.meal_type for template in get_slot_templates(meals_per_day)]


def _candidate_multipliers(*, extra_candidates: list[Decimal] | None = None) -> tuple[Decimal, ...]:
    values = set(SERVINGS_MULTIPLIER_CANDIDATES)
    for value in extra_candidates or []:
        if value > 0:
            values.add(value)
    return tuple(sorted(values))


def _normalize_target(value: int | None) -> Decimal | None:
    if value is None or value <= 0:
        return None
    return Decimal(value)


def _build_plan_targets(*, kcal: int | None, protein: int | None, fat: int | None, carbs: int | None) -> PlanTargets:
    return PlanTargets(
        kcal=_normalize_target(kcal),
        protein=_normalize_target(protein),
        fat=_normalize_target(fat),
        carbs=_normalize_target(carbs),
    )


def _resolve_profile_for_autogenerate(
    db: Session,
    *,
    user_id: int,
    profile_id: int | None,
) -> Profile:
    if profile_id is not None:
        profile = db.execute(
            select(Profile).where(
                Profile.id == profile_id,
                Profile.user_id == user_id,
            )
        ).scalar_one_or_none()
        if profile is None:
            raise PlanAutogenerateProfileNotFoundError("Profile not found")
        return profile

    profile = db.execute(
        select(Profile)
        .where(Profile.user_id == user_id)
        .order_by(Profile.id.asc())
        .limit(1)
    ).scalar_one_or_none()
    if profile is None:
        raise PlanAutogenerateProfileValidationError(
            "Profile is required for autogenerate. Create one or pass profile_id."
        )
    return profile


def _resolve_targets_from_profile(profile: Profile) -> PlanTargets:
    targets = _build_plan_targets(
        kcal=profile.target_kcal,
        protein=profile.target_protein,
        fat=profile.target_fat,
        carbs=profile.target_carbs,
    )
    if targets.kcal is None:
        raise PlanAutogenerateProfileValidationError(
            "Selected profile must have target_kcal > 0 for autogeneration."
        )
    return targets


def _resolve_targets_from_plan(plan: Plan) -> PlanTargets:
    return _build_plan_targets(
        kcal=plan.target_kcal,
        protein=plan.target_protein,
        fat=plan.target_fat,
        carbs=plan.target_carbs,
    )


def _normalize_recipe_meal_types(recipe: Recipe) -> set[str]:
    return {value.strip().lower() for value in recipe.meal_types}


def get_accessible_recipe_candidates(
    db: Session,
    *,
    user_id: int,
    meal_type: str,
    use_public_recipes: bool,
    excluded_recipe_ids: list[int],
    excluded_food_ids: list[int],
) -> list[Recipe]:
    excluded_recipe_ids_set = set(excluded_recipe_ids)
    excluded_food_ids_set = set(excluded_food_ids)

    stmt = (
        select(Recipe)
        .options(selectinload(Recipe.ingredients).selectinload(RecipeIngredient.food))
        .where(
            build_accessible_recipes_condition(
                user_id=user_id,
                include_public=use_public_recipes,
            )
        )
        .order_by(Recipe.id.asc())
    )
    if excluded_recipe_ids_set:
        stmt = stmt.where(Recipe.id.notin_(sorted(excluded_recipe_ids_set)))

    recipes = db.execute(stmt).scalars().all()
    candidates: list[Recipe] = []
    for recipe in recipes:
        if meal_type not in _normalize_recipe_meal_types(recipe):
            continue
        if excluded_food_ids_set and any(ingredient.food_id in excluded_food_ids_set for ingredient in recipe.ingredients):
            continue
        candidates.append(recipe)
    return candidates


def _raise_not_enough_recipes_error(*, meal_type: str, day_date: date) -> None:
    raise PlanAutogenerateNotEnoughRecipesError(
        f"Not enough recipes for meal_type={meal_type} on {day_date.isoformat()}"
    )


def _load_plan_with_slots_for_user(db: Session, *, user_id: int, plan_id: int) -> Plan:
    plan = db.execute(
        select(Plan)
        .where(Plan.id == plan_id, Plan.owner_user_id == user_id)
        .options(
            selectinload(Plan.profile),
            selectinload(Plan.slots)
            .selectinload(PlanSlot.recipe)
            .selectinload(Recipe.ingredients)
            .selectinload(RecipeIngredient.food),
        )
    ).scalar_one_or_none()
    if plan is None:
        raise PlanAutogeneratePlanNotFoundError("Plan not found")
    return plan


def _resolve_slot_template(*, meals_per_day: int, slot_index: int) -> SlotTemplate:
    templates = get_slot_templates(meals_per_day)
    if slot_index < 0 or slot_index >= len(templates):
        raise ValueError("Unsupported slot_index")
    return templates[slot_index]


def _build_recipe_usage_counts(
    *,
    slots: list[PlanSlot],
    excluded_slot_ids: set[int] | None = None,
) -> dict[int, int]:
    usage_counts: dict[int, int] = defaultdict(int)
    excluded_ids = excluded_slot_ids or set()
    for slot in slots:
        if slot.id in excluded_ids or slot.recipe_id is None:
            continue
        usage_counts[slot.recipe_id] += 1
    return usage_counts


def _build_slot_recipe_dates(
    *,
    slots: list[PlanSlot],
    excluded_slot_ids: set[int] | None = None,
) -> dict[int, dict[int, list[date]]]:
    grouped: dict[int, dict[int, list[date]]] = defaultdict(lambda: defaultdict(list))
    excluded_ids = excluded_slot_ids or set()
    for slot in slots:
        if slot.id in excluded_ids or slot.recipe_id is None:
            continue
        grouped[slot.slot_index][slot.recipe_id].append(slot.day_date)

    for by_recipe in grouped.values():
        for recipe_dates in by_recipe.values():
            recipe_dates.sort()
    return grouped


def _build_recipe_lookup(*, slots: list[PlanSlot], extra_recipes: list[Recipe] | None = None) -> dict[int, Recipe]:
    lookup: dict[int, Recipe] = {}
    for slot in slots:
        if slot.recipe_id is None or slot.recipe is None:
            continue
        lookup[slot.recipe_id] = slot.recipe

    for recipe in extra_recipes or []:
        lookup[recipe.id] = recipe
    return lookup


def _zero_totals() -> dict[str, Decimal]:
    return {
        "kcal": Decimal("0"),
        "protein": Decimal("0"),
        "fat": Decimal("0"),
        "carbs": Decimal("0"),
    }


def _add_totals(
    totals: dict[str, Decimal],
    *,
    nutrients: dict[str, Decimal],
    servings_multiplier: Decimal,
) -> None:
    totals["kcal"] += nutrients["kcal"] * servings_multiplier
    totals["protein"] += nutrients["protein"] * servings_multiplier
    totals["fat"] += nutrients["fat"] * servings_multiplier
    totals["carbs"] += nutrients["carbs"] * servings_multiplier


def _recipe_nutrients_per_serving(
    recipe: Recipe,
    *,
    recipe_nutrients_cache: dict[int, dict[str, Decimal]],
) -> dict[str, Decimal]:
    cached = recipe_nutrients_cache.get(recipe.id)
    if cached is not None:
        return cached

    nutrients = calculate_recipe_nutrients(recipe)
    normalized = {
        "kcal": nutrients["per_serving_kcal"],
        "protein": nutrients["per_serving_protein"],
        "fat": nutrients["per_serving_fat"],
        "carbs": nutrients["per_serving_carbs"],
    }
    recipe_nutrients_cache[recipe.id] = normalized
    return normalized


def _calculate_day_totals_before_slot(
    *,
    day_slots: list[PlanSlot],
    target_slot_index: int,
    selected_slot_candidate_by_slot_id: dict[int, tuple[int, Decimal]],
    recipe_by_id: dict[int, Recipe],
    recipe_nutrients_cache: dict[int, dict[str, Decimal]],
) -> dict[str, Decimal]:
    totals = _zero_totals()
    for slot in day_slots:
        if slot.slot_index >= target_slot_index:
            continue

        if slot.id in selected_slot_candidate_by_slot_id:
            recipe_id, servings_multiplier = selected_slot_candidate_by_slot_id[slot.id]
        else:
            recipe_id = slot.recipe_id
            servings_multiplier = slot.servings_multiplier

        if recipe_id is None:
            continue

        recipe = recipe_by_id.get(recipe_id)
        if recipe is None:
            continue

        nutrients = _recipe_nutrients_per_serving(recipe, recipe_nutrients_cache=recipe_nutrients_cache)
        _add_totals(totals, nutrients=nutrients, servings_multiplier=servings_multiplier)
    return totals


def _relative_penalty(actual: Decimal, expected: Decimal | None, *, weight: Decimal) -> Decimal:
    if expected is None or expected <= 0:
        return Decimal("0")
    return (abs(actual - expected) / expected) * weight


def _overshoot_ratio(actual: Decimal, target: Decimal | None) -> Decimal:
    if target is None or target <= 0:
        return Decimal("0")
    if actual <= target:
        return Decimal("0")
    return (actual - target) / target


def _undershoot_ratio(actual: Decimal, target: Decimal | None) -> Decimal:
    if target is None or target <= 0:
        return Decimal("0")
    if actual >= target:
        return Decimal("0")
    return (target - actual) / target


def _piecewise_penalty(
    ratio: Decimal,
    *,
    weight: Decimal,
    mild_ratio: Decimal = Decimal("0.10"),
    sharp_ratio: Decimal = Decimal("0.25"),
) -> Decimal:
    if ratio <= 0:
        return Decimal("0")

    mild_part = min(ratio, mild_ratio)
    penalty = mild_part * weight

    if ratio > mild_ratio:
        moderate_part = min(ratio, sharp_ratio) - mild_ratio
        penalty += moderate_part * weight * Decimal("2.5")

    if ratio > sharp_ratio:
        severe_part = ratio - sharp_ratio
        penalty += severe_part * weight * Decimal("4.0")

    return penalty


def _macro_energy_shares(nutrients: dict[str, Decimal]) -> tuple[Decimal, Decimal, Decimal]:
    protein_energy = nutrients["protein"] * Decimal("4")
    fat_energy = nutrients["fat"] * Decimal("9")
    carbs_energy = nutrients["carbs"] * Decimal("4")
    total_energy = protein_energy + fat_energy + carbs_energy
    if total_energy <= 0:
        return Decimal("0"), Decimal("0"), Decimal("0")
    return (
        protein_energy / total_energy,
        fat_energy / total_energy,
        carbs_energy / total_energy,
    )


def is_protein_heavy(nutrients: dict[str, Decimal]) -> bool:
    protein_share, _fat_share, carbs_share = _macro_energy_shares(nutrients)
    return protein_share >= Decimal("0.34") and carbs_share <= Decimal("0.35")


def is_carb_heavy(nutrients: dict[str, Decimal]) -> bool:
    _protein_share, _fat_share, carbs_share = _macro_energy_shares(nutrients)
    return carbs_share >= Decimal("0.48")


def is_fat_heavy(nutrients: dict[str, Decimal]) -> bool:
    _protein_share, fat_share, _carbs_share = _macro_energy_shares(nutrients)
    return fat_share >= Decimal("0.42")


def is_balanced_macro_profile(nutrients: dict[str, Decimal]) -> bool:
    protein_share, fat_share, carbs_share = _macro_energy_shares(nutrients)
    return (
        Decimal("0.18") <= protein_share <= Decimal("0.35")
        and Decimal("0.20") <= fat_share <= Decimal("0.40")
        and Decimal("0.30") <= carbs_share <= Decimal("0.60")
    )


def _max_multiplier_for_recipe(nutrients: dict[str, Decimal]) -> Decimal:
    if nutrients["protein"] >= PROTEIN_DENSE_PER_SERVING_THRESHOLD:
        return PROTEIN_DENSE_MULTIPLIER_CAP
    if is_protein_heavy(nutrients) and nutrients["carbs"] <= LOW_CARB_PER_SERVING_THRESHOLD:
        return PROTEIN_DENSE_MULTIPLIER_CAP
    return max(SERVINGS_MULTIPLIER_CANDIDATES)


def _cumulative_weight_for_slot(*, meals_per_day: int, slot_index: int) -> Decimal:
    templates = get_slot_templates(meals_per_day)
    return sum(template.weight for template in templates[: slot_index + 1])


def _calculate_repeat_penalty(
    *,
    recipe_id: int,
    slot_index: int,
    day_date: date,
    recipe_usage_counts: dict[int, int],
    slot_recipe_dates: dict[int, dict[int, list[date]]],
) -> Decimal:
    penalty = Decimal(recipe_usage_counts.get(recipe_id, 0)) * REPEAT_USAGE_PENALTY

    same_slot_dates = slot_recipe_dates.get(slot_index, {}).get(recipe_id, [])
    for existing_day in same_slot_dates:
        distance = abs((day_date - existing_day).days)
        if distance == 0:
            continue
        if distance in REPEAT_SAME_SLOT_BY_DISTANCE:
            penalty += REPEAT_SAME_SLOT_BY_DISTANCE[distance]
        elif distance <= 7:
            penalty += FAR_REPEAT_SAME_SLOT_PENALTY

    return penalty


def _score_recipe_candidate(
    recipe: Recipe,
    *,
    day_date: date,
    slot_index: int,
    expected_meal_type: str,
    day_totals_before_slot: dict[str, Decimal],
    slot_weight: Decimal,
    servings_multiplier: Decimal,
    cumulative_weight: Decimal,
    targets: PlanTargets,
    recipe_usage_counts: dict[int, int],
    slot_recipe_dates: dict[int, dict[int, list[date]]],
    recipe_nutrients: dict[str, Decimal],
) -> RecipeScore:
    nutrients = recipe_nutrients

    projected_day_kcal = day_totals_before_slot["kcal"] + nutrients["kcal"] * servings_multiplier
    projected_day_protein = day_totals_before_slot["protein"] + nutrients["protein"] * servings_multiplier
    projected_day_fat = day_totals_before_slot["fat"] + nutrients["fat"] * servings_multiplier
    projected_day_carbs = day_totals_before_slot["carbs"] + nutrients["carbs"] * servings_multiplier

    expected_kcal = targets.kcal * cumulative_weight if targets.kcal is not None else None
    expected_protein = targets.protein * cumulative_weight if targets.protein is not None else None
    expected_fat = targets.fat * cumulative_weight if targets.fat is not None else None
    expected_carbs = targets.carbs * cumulative_weight if targets.carbs is not None else None

    calorie_penalty = _relative_penalty(projected_day_kcal, expected_kcal, weight=CALORIE_PENALTY_WEIGHT)
    cumulative_macro_penalty = (
        _relative_penalty(projected_day_protein, expected_protein, weight=MACRO_PENALTY_WEIGHT)
        + _relative_penalty(projected_day_fat, expected_fat, weight=MACRO_PENALTY_WEIGHT)
        + _relative_penalty(projected_day_carbs, expected_carbs, weight=MACRO_PENALTY_WEIGHT)
    )

    protein_overshoot_penalty = _piecewise_penalty(
        _overshoot_ratio(projected_day_protein, targets.protein),
        weight=PROTEIN_OVERSHOOT_WEIGHT,
    )
    fat_overshoot_penalty = _piecewise_penalty(
        _overshoot_ratio(projected_day_fat, targets.fat),
        weight=FAT_OVERSHOOT_WEIGHT,
    )
    carbs_undershoot_penalty = _piecewise_penalty(
        _undershoot_ratio(projected_day_carbs, targets.carbs),
        weight=CARBS_UNDERSHOOT_WEIGHT,
    )

    remaining_balance_penalty = Decimal("0")
    remaining_weight = max(Decimal("0"), Decimal("1") - cumulative_weight)
    if targets.carbs is not None and targets.carbs > 0 and remaining_weight > 0:
        remaining_carbs_needed = max(Decimal("0"), targets.carbs - projected_day_carbs)
        expected_remaining_carbs = targets.carbs * remaining_weight
        if remaining_carbs_needed > expected_remaining_carbs:
            remaining_balance_penalty += _piecewise_penalty(
                (remaining_carbs_needed - expected_remaining_carbs) / expected_remaining_carbs,
                weight=REMAINING_BALANCE_WEIGHT,
            )
    if targets.protein is not None and targets.protein > 0 and remaining_weight > 0:
        remaining_protein_budget = max(Decimal("0"), targets.protein - projected_day_protein)
        expected_remaining_protein = targets.protein * remaining_weight
        tight_budget = expected_remaining_protein * Decimal("0.50")
        if tight_budget > 0 and remaining_protein_budget < tight_budget:
            remaining_balance_penalty += _piecewise_penalty(
                (tight_budget - remaining_protein_budget) / tight_budget,
                weight=REMAINING_BALANCE_WEIGHT,
                mild_ratio=Decimal("0.08"),
                sharp_ratio=Decimal("0.20"),
            )

    macro_profile_penalty = Decimal("0")
    carbs_so_far_deficit_ratio = _undershoot_ratio(projected_day_carbs, expected_carbs)
    protein_overshoot_ratio = _overshoot_ratio(projected_day_protein, targets.protein)
    if carbs_so_far_deficit_ratio > Decimal("0.10"):
        if is_protein_heavy(nutrients) and not is_carb_heavy(nutrients):
            macro_profile_penalty += carbs_so_far_deficit_ratio * MACRO_PROFILE_PENALTY_WEIGHT * Decimal("1.8")
        elif is_balanced_macro_profile(nutrients):
            macro_profile_penalty += carbs_so_far_deficit_ratio * MACRO_PROFILE_PENALTY_WEIGHT * Decimal("0.5")
        else:
            macro_profile_penalty += carbs_so_far_deficit_ratio * MACRO_PROFILE_PENALTY_WEIGHT
    if protein_overshoot_ratio > Decimal("0.05") and is_protein_heavy(nutrients):
        macro_profile_penalty += protein_overshoot_ratio * MACRO_PROFILE_PENALTY_WEIGHT * Decimal("1.6")
    if is_fat_heavy(nutrients) and _overshoot_ratio(projected_day_fat, targets.fat) > Decimal("0.05"):
        macro_profile_penalty += _overshoot_ratio(projected_day_fat, targets.fat) * MACRO_PROFILE_PENALTY_WEIGHT

    guardrail_penalty = Decimal("0")
    if (
        targets.protein is not None
        and targets.protein > 0
        and projected_day_protein > (targets.protein * PROTEIN_OVERSHOOT_HARD_LIMIT)
    ):
        guardrail_penalty += HUGE_GUARDRAIL_PENALTY

    if (
        targets.carbs is not None
        and expected_carbs is not None
        and expected_carbs > 0
        and slot_weight >= LARGE_SLOT_WEIGHT_THRESHOLD
        and projected_day_carbs < (expected_carbs * CARBS_SO_FAR_GUARDRAIL_RATIO)
    ):
        guardrail_penalty += HUGE_GUARDRAIL_PENALTY

    if (
        servings_multiplier > PROTEIN_DENSE_MULTIPLIER_THRESHOLD
        and is_protein_heavy(nutrients)
        and nutrients["carbs"] <= LOW_CARB_PER_SERVING_THRESHOLD
    ):
        guardrail_penalty += HUGE_GUARDRAIL_PENALTY

    if expected_kcal is not None and expected_kcal > 0:
        kcal_so_far_deviation = abs(projected_day_kcal - expected_kcal) / expected_kcal
        carbs_so_far_ratio = Decimal("1")
        if expected_carbs is not None and expected_carbs > 0:
            carbs_so_far_ratio = projected_day_carbs / expected_carbs
        if kcal_so_far_deviation <= Decimal("0.15") and (
            protein_overshoot_ratio >= Decimal("0.20") or carbs_so_far_ratio <= Decimal("0.70")
        ):
            guardrail_penalty += HUGE_GUARDRAIL_PENALTY / Decimal("2")

    macro_penalty = (
        cumulative_macro_penalty
        + protein_overshoot_penalty
        + fat_overshoot_penalty
        + carbs_undershoot_penalty
        + remaining_balance_penalty
        + macro_profile_penalty
        + guardrail_penalty
    )

    slot_penalty = Decimal("0")
    if expected_meal_type not in _normalize_recipe_meal_types(recipe):
        slot_penalty = SLOT_MISMATCH_PENALTY

    repeat_penalty = _calculate_repeat_penalty(
        recipe_id=recipe.id,
        slot_index=slot_index,
        day_date=day_date,
        recipe_usage_counts=recipe_usage_counts,
        slot_recipe_dates=slot_recipe_dates,
    )

    return RecipeScore(
        total_score=calorie_penalty + macro_penalty + slot_penalty + repeat_penalty,
        repeat_penalty=repeat_penalty,
        calorie_penalty=calorie_penalty,
        macro_penalty=macro_penalty,
        slot_penalty=slot_penalty,
    )


def _select_slot_candidate(
    *,
    candidates: list[Recipe],
    multiplier_candidates: tuple[Decimal, ...],
    expected_meal_type: str,
    day_date: date,
    slot_index: int,
    day_totals_before_slot: dict[str, Decimal],
    slot_weight: Decimal,
    cumulative_weight: Decimal,
    targets: PlanTargets,
    recipe_usage_counts: dict[int, int],
    slot_recipe_dates: dict[int, dict[int, list[date]]],
    recipe_nutrients_cache: dict[int, dict[str, Decimal]],
) -> tuple[Recipe, Decimal]:
    if not candidates:
        _raise_not_enough_recipes_error(meal_type=expected_meal_type, day_date=day_date)

    best: tuple[Recipe, Decimal] | None = None
    best_key: tuple[Decimal, Decimal, Decimal, int, Decimal] | None = None

    for recipe in candidates:
        recipe_nutrients = _recipe_nutrients_per_serving(recipe, recipe_nutrients_cache=recipe_nutrients_cache)
        max_multiplier = _max_multiplier_for_recipe(recipe_nutrients)
        for multiplier in multiplier_candidates:
            if multiplier > max_multiplier:
                continue
            score = _score_recipe_candidate(
                recipe,
                day_date=day_date,
                slot_index=slot_index,
                expected_meal_type=expected_meal_type,
                day_totals_before_slot=day_totals_before_slot,
                slot_weight=slot_weight,
                servings_multiplier=multiplier,
                cumulative_weight=cumulative_weight,
                targets=targets,
                recipe_usage_counts=recipe_usage_counts,
                slot_recipe_dates=slot_recipe_dates,
                recipe_nutrients=recipe_nutrients,
            )
            candidate_key = (
                score.total_score,
                score.repeat_penalty,
                score.calorie_penalty,
                recipe.id,
                multiplier,
            )
            if best_key is None or candidate_key < best_key:
                best = (recipe, multiplier)
                best_key = candidate_key

    if best is None:
        _raise_not_enough_recipes_error(meal_type=expected_meal_type, day_date=day_date)
    return best


def build_autogenerated_plan(
    db: Session,
    *,
    user_id: int,
    payload: PlanAutogenerateRequest,
) -> Plan:
    selected_profile = _resolve_profile_for_autogenerate(
        db,
        user_id=user_id,
        profile_id=payload.profile_id,
    )
    targets = _resolve_targets_from_profile(selected_profile)

    slot_templates = get_slot_templates(payload.meals_per_day)

    candidates_by_meal_type: dict[str, list[Recipe]] = {}
    for meal_type in sorted({template.meal_type for template in slot_templates}):
        candidates_by_meal_type[meal_type] = get_accessible_recipe_candidates(
            db,
            user_id=user_id,
            meal_type=meal_type,
            use_public_recipes=payload.use_public_recipes,
            excluded_recipe_ids=payload.excluded_recipe_ids,
            excluded_food_ids=payload.excluded_food_ids,
        )

    planned_slots: list[tuple[date, int, int, Decimal]] = []
    recipe_usage_counts: dict[int, int] = defaultdict(int)
    slot_recipe_dates: dict[int, dict[int, list[date]]] = defaultdict(lambda: defaultdict(list))
    recipe_nutrients_cache: dict[int, dict[str, Decimal]] = {}

    for day_offset in range(payload.days_count):
        day_date = payload.start_date + timedelta(days=day_offset)
        day_totals = _zero_totals()

        cumulative_weight = Decimal("0")
        for slot_index, template in enumerate(slot_templates):
            cumulative_weight += template.weight
            selected_recipe, selected_multiplier = _select_slot_candidate(
                candidates=candidates_by_meal_type[template.meal_type],
                multiplier_candidates=_candidate_multipliers(),
                expected_meal_type=template.meal_type,
                day_date=day_date,
                slot_index=slot_index,
                day_totals_before_slot=day_totals,
                slot_weight=template.weight,
                cumulative_weight=cumulative_weight,
                targets=targets,
                recipe_usage_counts=recipe_usage_counts,
                slot_recipe_dates=slot_recipe_dates,
                recipe_nutrients_cache=recipe_nutrients_cache,
            )

            selected_nutrients = _recipe_nutrients_per_serving(
                selected_recipe,
                recipe_nutrients_cache=recipe_nutrients_cache,
            )
            _add_totals(
                day_totals,
                nutrients=selected_nutrients,
                servings_multiplier=selected_multiplier,
            )

            planned_slots.append((day_date, slot_index, selected_recipe.id, selected_multiplier))
            recipe_usage_counts[selected_recipe.id] += 1
            slot_recipe_dates[slot_index][selected_recipe.id].append(day_date)

    plan = Plan(
        owner_user_id=user_id,
        profile_id=selected_profile.id,
        start_date=payload.start_date,
        days_count=payload.days_count,
        meals_per_day=payload.meals_per_day,
        title=None,
        target_kcal=selected_profile.target_kcal,
        target_protein=selected_profile.target_protein,
        target_fat=selected_profile.target_fat,
        target_carbs=selected_profile.target_carbs,
    )
    db.add(plan)
    db.flush()

    slots = [
        PlanSlot(
            plan_id=plan.id,
            day_date=day_date,
            slot_index=slot_index,
            recipe_id=recipe_id,
            servings_multiplier=servings_multiplier,
            pinned=False,
        )
        for day_date, slot_index, recipe_id, servings_multiplier in planned_slots
    ]
    db.add_all(slots)

    try:
        db.commit()
    except Exception:
        db.rollback()
        raise

    return _load_plan_with_slots_for_user(db, user_id=user_id, plan_id=plan.id)


def replace_plan_slot(
    db: Session,
    *,
    user_id: int,
    plan_id: int,
    slot_id: int,
    payload: ReplacePlanSlotRequest,
) -> Plan:
    plan = _load_plan_with_slots_for_user(db, user_id=user_id, plan_id=plan_id)
    slot = next((value for value in plan.slots if value.id == slot_id), None)
    if slot is None:
        raise PlanAutogenerateSlotNotFoundError("Plan slot not found")

    targets = _resolve_targets_from_plan(plan)
    template = _resolve_slot_template(meals_per_day=plan.meals_per_day, slot_index=slot.slot_index)

    candidates = get_accessible_recipe_candidates(
        db,
        user_id=user_id,
        meal_type=template.meal_type,
        use_public_recipes=payload.use_public_recipes,
        excluded_recipe_ids=payload.excluded_recipe_ids,
        excluded_food_ids=payload.excluded_food_ids,
    )

    avoid_recipe_ids: set[int] = set()
    if payload.avoid_current_recipe and slot.recipe_id is not None:
        avoid_recipe_ids.add(slot.recipe_id)
    if avoid_recipe_ids:
        candidates = [candidate for candidate in candidates if candidate.id not in avoid_recipe_ids]

    day_slots = sorted(
        [value for value in plan.slots if value.day_date == slot.day_date],
        key=lambda value: (value.slot_index, value.id),
    )

    recipe_usage_counts = _build_recipe_usage_counts(slots=list(plan.slots), excluded_slot_ids={slot.id})
    slot_recipe_dates = _build_slot_recipe_dates(slots=list(plan.slots), excluded_slot_ids={slot.id})

    recipe_by_id = _build_recipe_lookup(slots=list(plan.slots), extra_recipes=candidates)
    recipe_nutrients_cache: dict[int, dict[str, Decimal]] = {}

    day_totals_before_slot = _calculate_day_totals_before_slot(
        day_slots=day_slots,
        target_slot_index=slot.slot_index,
        selected_slot_candidate_by_slot_id={},
        recipe_by_id=recipe_by_id,
        recipe_nutrients_cache=recipe_nutrients_cache,
    )

    selected_recipe, selected_multiplier = _select_slot_candidate(
        candidates=candidates,
        multiplier_candidates=_candidate_multipliers(extra_candidates=[slot.servings_multiplier]),
        expected_meal_type=template.meal_type,
        day_date=slot.day_date,
        slot_index=slot.slot_index,
        day_totals_before_slot=day_totals_before_slot,
        slot_weight=template.weight,
        cumulative_weight=_cumulative_weight_for_slot(meals_per_day=plan.meals_per_day, slot_index=slot.slot_index),
        targets=targets,
        recipe_usage_counts=recipe_usage_counts,
        slot_recipe_dates=slot_recipe_dates,
        recipe_nutrients_cache=recipe_nutrients_cache,
    )

    slot.recipe_id = selected_recipe.id
    slot.servings_multiplier = selected_multiplier
    try:
        db.commit()
    except Exception:
        db.rollback()
        raise

    return _load_plan_with_slots_for_user(db, user_id=user_id, plan_id=plan.id)


def regenerate_plan_day(
    db: Session,
    *,
    user_id: int,
    plan_id: int,
    day_date: date,
    payload: RegeneratePlanDayRequest,
) -> Plan:
    plan = _load_plan_with_slots_for_user(db, user_id=user_id, plan_id=plan_id)
    end_date = plan.start_date + timedelta(days=plan.days_count - 1)
    if day_date < plan.start_date or day_date > end_date:
        raise PlanAutogenerateDayOutOfRangeError(
            f"Day {day_date.isoformat()} is out of plan range"
        )

    day_slots = sorted(
        [slot for slot in plan.slots if slot.day_date == day_date],
        key=lambda slot: (slot.slot_index, slot.id),
    )
    mutable_slots = [slot for slot in day_slots if not slot.pinned]
    if not mutable_slots:
        return plan

    targets = _resolve_targets_from_plan(plan)

    mutable_slot_ids = {slot.id for slot in mutable_slots}
    recipe_usage_counts = _build_recipe_usage_counts(
        slots=list(plan.slots),
        excluded_slot_ids=mutable_slot_ids,
    )
    slot_recipe_dates = _build_slot_recipe_dates(
        slots=list(plan.slots),
        excluded_slot_ids=mutable_slot_ids,
    )

    selected_slot_candidate_by_slot_id: dict[int, tuple[int, Decimal]] = {}
    recipe_by_id = _build_recipe_lookup(slots=list(plan.slots))
    recipe_nutrients_cache: dict[int, dict[str, Decimal]] = {}

    for slot in mutable_slots:
        template = _resolve_slot_template(meals_per_day=plan.meals_per_day, slot_index=slot.slot_index)
        candidates = get_accessible_recipe_candidates(
            db,
            user_id=user_id,
            meal_type=template.meal_type,
            use_public_recipes=payload.use_public_recipes,
            excluded_recipe_ids=payload.excluded_recipe_ids,
            excluded_food_ids=payload.excluded_food_ids,
        )
        for recipe in candidates:
            recipe_by_id[recipe.id] = recipe

        day_totals_before_slot = _calculate_day_totals_before_slot(
            day_slots=day_slots,
            target_slot_index=slot.slot_index,
            selected_slot_candidate_by_slot_id=selected_slot_candidate_by_slot_id,
            recipe_by_id=recipe_by_id,
            recipe_nutrients_cache=recipe_nutrients_cache,
        )

        selected_recipe, selected_multiplier = _select_slot_candidate(
            candidates=candidates,
            multiplier_candidates=_candidate_multipliers(extra_candidates=[slot.servings_multiplier]),
            expected_meal_type=template.meal_type,
            day_date=day_date,
            slot_index=slot.slot_index,
            day_totals_before_slot=day_totals_before_slot,
            slot_weight=template.weight,
            cumulative_weight=_cumulative_weight_for_slot(meals_per_day=plan.meals_per_day, slot_index=slot.slot_index),
            targets=targets,
            recipe_usage_counts=recipe_usage_counts,
            slot_recipe_dates=slot_recipe_dates,
            recipe_nutrients_cache=recipe_nutrients_cache,
        )

        selected_slot_candidate_by_slot_id[slot.id] = (selected_recipe.id, selected_multiplier)
        recipe_usage_counts[selected_recipe.id] += 1
        slot_recipe_dates[slot.slot_index][selected_recipe.id].append(day_date)

    for slot in mutable_slots:
        selected_recipe_id, selected_multiplier = selected_slot_candidate_by_slot_id[slot.id]
        slot.recipe_id = selected_recipe_id
        slot.servings_multiplier = selected_multiplier

    try:
        db.commit()
    except Exception:
        db.rollback()
        raise

    return _load_plan_with_slots_for_user(db, user_id=user_id, plan_id=plan.id)
